In [2]:
import pandas as pd

df = pd.read_csv("nba_draft_combine_wingspan.csv")
df.head()

,draft_year,overall_pick,round_number,round_pick,player_id,player_name,position,team_abbreviation,organization,height_wo_shoes,wingspan,wingspan_diff
0,2015,2,1,2,1626156,D'Angelo Russell,PG-SG,LAL,Ohio State,75.25,81.75,6.50
1,2015,6,1,6,1626161,Willie Cauley-Stein,C,SAC,Kentucky,83.25,87.00,3.75
2,2015,8,1,8,1626169,Stanley Johnson,SF,DET,Arizona,77.00,83.50,6.50
3,2015,9,1,9,1626163,Frank Kaminsky,C-PF,CHA,Wisconsin,83.75,83.00,-0.75
4,2015,10,1,10,1626159,Justise Winslow,SF,MIA,Duke,76.50,82.25,5.75

In [3]:
print(f"Total rows: {len(df)}")

Total rows: 409

In [5]:
df.shape

(409, 12)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   draft_year         409 non-null    int64
 1   overall_pick       409 non-null    int64
 2   round_number       409 non-null    int64
 3   round_pick         409 non-null    int64
 4   player_id          409 non-null    int64
 5   player_name        409 non-null    str
 6   position           409 non-null    str
 7   team_abbreviation  409 non-null    str
 8   organization       408 non-null    str
 9   height_wo_shoes    409 non-null    float64
 10  wingspan           409 non-null    float64
 11  wingspan_diff      409 non-null    float64
dtypes: float64(3), int64(5), str(4)
memory usage: 38.5 KB

In [8]:
df.isna().sum()

draft_year           0
overall_pick         0
round_number         0
round_pick           0
player_id            0
player_name          0
position             0
team_abbreviation    0
organization         1
height_wo_shoes      0
wingspan             0
wingspan_diff        0
dtype: int64

In [4]:
df.describe()

,draft_year,overall_pick,round_number,round_pick,player_id,height_wo_shoes,wingspan,wingspan_diff
count,409.000000,409.000000,409.000000,409.000000,4.090000e+02,409.000000,409.000000,409.000000
mean,2019.706601,31.396088,1.513447,15.992665,1.627857e+06,77.676039,82.506724,4.830685
std,2.976539,15.857193,0.500431,8.168114,8.077212e+04,3.045539,3.656990,2.194488
min,2015.000000,1.000000,1.000000,1.000000,2.006000e+03,68.250000,73.750000,-1.750000
25%,2017.000000,18.000000,1.000000,9.000000,1.628407e+06,75.750000,80.000000,3.500000
50%,2020.000000,31.000000,2.000000,16.000000,1.629673e+06,77.500000,82.250000,4.750000
75%,2022.000000,45.000000,2.000000,23.000000,1.631159e+06,80.000000,85.250000,6.250000
max,2024.000000,60.000000,2.000000,30.000000,1.642402e+06,87.750000,94.750000,10.750000